include(":PlayableEmbeds")
// include(":AliuEval")
// include(":EmojiReplacer")
// include(":OwO")
// include(":ShowBlockedMessages")
include(":BetterSpotify")
// include(":Brainfuck")
// include(":CheckLinks")
// include(":AnimateApngs")
// include(":DedicatedPluginSettings")
// include(":Themer")
// include(":ViewProfileImages")
// include(":TapTap")
// include(":MessageLinkEmbeds")
// include(":EmojiUtility")
// include(":PluginDownloader")
// include(":Hastebin")
// include(":UrbanDictionary")

rootProject.name = "AliucordPlugins"
