include(":GatewayLog")
include(":TextFilePreview")
// include(":SnowflakeLookup")
include(":FixEmotes")
include(":PlayableEmbeds")
// include(":AliuEval")
// include(":OwO")
include(":EmojiReplacer")
include(":ShowBlockedMessages")
include(":BetterSpotify")
include(":Brainfuck")
include(":CheckLinks")
include(":AnimateApngs")
include(":DedicatedPluginSettings")
include(":Themer")
include(":ViewProfileImages")
include(":TapTap")
include(":MessageLinkEmbeds")
include(":EmojiUtility")
include(":Hastebin")
include(":UrbanDictionary")

rootProject.name = "AliucordPlugins"
